name: django-test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode DJANGO_KEY
        run:  echo ${{secrets.DJANGO_KEY}} > ./.env

      - name: Decode CLOUD_SQL_KEY
        run: printf "${{secrets.CLOUD_SQL_KEY}}" >> ./.env

      - name: Run django test
        run:  python manage.py test

