name: django-test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Decode DJANGO_KEY
        run:  echo ${{secrets.DJANGO_KEY}} > ./.env
      - name: Run Django Test
        run:  python manage.py test
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}

