name: django-deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          credentials_file_path: './gcp.json'

      - name: Set gcloud project
        run: gcloud config set project file-sorting-root-tracking

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode DJANGO_KEY
        run:  echo ${{secrets.DJANGO_KEY}} > ./.env

      - name: Decode CLOUD_SQL_KEY
        run: printf "${{secrets.CLOUD_SQL_KEY}}" >> ./env

      - name: Move static files
        run: python manage.py collectstatic

      - name: Deploy
        run: gcloud app deploy

